# Generated by Django 4.1 on 2023-03-06 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Devices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_code', models.IntegerField()),
                ('account_name', models.TextField()),
                ('campaign_code', models.IntegerField()),
                ('currency', models.TextField()),
                ('cost', models.FloatField()),
                ('conversions', models.FloatField()),
                ('impressions', models.FloatField()),
                ('clicks', models.IntegerField()),
                ('account_timezone', models.TextField()),
                ('network_type', models.TextField()),
                ('timestamp', models.DateTimeField()),
            ],
        ),
    ]
