# Generated by Django 4.1 on 2023-03-06 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devices',
            name='account_code',
            field=models.PositiveBigIntegerField(),
        ),
        migrations.AlterField(
            model_name='devices',
            name='campaign_code',
            field=models.PositiveBigIntegerField(),
        ),
    ]
