# Generated by Django 4.1 on 2023-03-06 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0002_alter_devices_account_code_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Devices',
            new_name='Ads',
        ),
    ]
